# Generated by Django 4.2.3 on 2024-07-31 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paliers',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comission.vendeurs', verbose_name='Vendeur'),
        ),
    ]
