# Generated by Django 4.2.3 on 2024-07-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comission', '0002_paliers_vendeur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paliers',
            new_name='Palier',
        ),
        migrations.RenameModel(
            old_name='Vendeurs',
            new_name='Vendeur',
        ),
        migrations.AlterModelOptions(
            name='palier',
            options={'ordering': ['external_id'], 'verbose_name': 'Palier'},
        ),
        migrations.AlterModelOptions(
            name='vendeur',
            options={'ordering': ['external_id_v'], 'verbose_name': 'Vendeur'},
        ),
        migrations.AlterModelTable(
            name='palier',
            table='palier_palier',
        ),
        migrations.AlterModelTable(
            name='vendeur',
            table='vendeur_vendeur',
        ),
    ]
