# Generated by Django 5.0.7 on 2024-08-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comission', '0003_rename_paliers_palier_rename_vendeurs_vendeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palier',
            name='external_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='palier',
            name='qte',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='external_id_v',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du Vendeur'),
        ),
    ]
