# Generated by Django 5.0.7 on 2024-08-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comission', '0005_vendeurpdv_rename_palier_palieragricole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palieragricole',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='palierpdv',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
