# Generated by Django 5.0.7 on 2024-08-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comission', '0006_alter_palieragricole_total_alter_palierpdv_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palieragricole',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='palierpdv',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
    ]
